### PR TITLE
Add Bluetooth permission

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR adds the Web Bluetooth API permission. See http://webbluetoothcg.github.io/web-bluetooth/

screenshot 2016-04-05 at 8 39 27 am

### CODE REVIEW

**Comment by adrifelt** [comment]
Does Bluetooth directly work or are there any instructions (e.g., flipping a flag) that should be added to the table of notes at the bottom?

**Comment by beaufortfrancois** [comment]
We need a flag, let me add one for Web Bluetooth & Web USB then.
Thanks for reviewing.

**Comment by beaufortfrancois** [comment]
@adrifelt I've added some notes.

**Comment by lgarron** [comment]
LGTM with the flag note. Thanks for the addition!

screen shot 2016-04-05 at 12 55 28

**Comment by lgarron** [comment]
Merged and deployed. :-)

**Comment by beaufortfrancois** [comment]
Yeah!

**Pull request merged**
