### PR TITLE
Add Origin trial token needed for Web Bluetooth

### PR DESCRIPTION
**Pull request by beaufortfrancois**
BUG=https://crbug.com/601153

### CODE REVIEW

**Comment by lgarron** [comment]
Do I need to do anything except upload the version of the site with the token?

screen shot 2016-04-15 at 11 34 24

**Comment by beaufortfrancois** [comment]
Nope.
When https://codereview.chromium.org/1858763003/ reaches Canary, it should work out of the box.

**Comment by lgarron** [comment]
> When https://codereview.chromium.org/1858763003/ reaches Canary, it should work out of the box.

It should definitely be on Canary right now, but I'm still getting the same error on OSX. :-(

**Comment by beaufortfrancois** [comment]
You're right... ;(
I'll follow up with @clelland

**Comment by jpchase** [comment]
On behalf of @clelland, I took a look at this pull request.  The meta tag should be specified as  `<meta http-equiv="origin-trial" content="token">`.  This pull request is using the old meta tag format. There was a change to the implementation in M50 to use the `http-equiv` attribute (instead of `name`) and the singular "origin-trial" name (instead of "origin-trials").

Our apologies if that change wasn't communicated clearly or broadly enough.

**Comment by lgarron** [comment]
Hmm, using the updated syntax makes the origin trial warning go away, but `navigator.bluetooth` is still not defined.

**Comment by beaufortfrancois** [comment]
The updated syntax works but not on Mac OS (only Android & Chrome OS for now).
You should get a message like that:

screen shot 2016-04-20 at 1 49 13 pm

**Comment by beaufortfrancois** [comment]
I've updated my patch to fit with new format

**Comment by lgarron** [comment]
Thanks!
I've updated Canary, and I now see the same message as your screenshot, but it's not formatted the same way. I've filed https://crbug.com/605215 for that.

**Pull request merged**
